apiVersion: v2
name: huber
description: A Helm chart for huber
type: application
version: 1.0.2
appVersion: 0.4.0
sources:
- https://github.com/NeCTAR-RC/huber-helm.git
dependencies:
- name: nectarlib
  version: 4.0.2
  repository: oci://registry.rc.nectar.org.au/nectar-helm
